require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

platform :ios, '10.0'

target 'RNPractice' do
  config = use_native_modules!
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  use_react_native!(:path => config["reactNativePath"])

  target 'RNPracticeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNPractice-tvOS' do
  # Pods for RNPractice-tvOS

  target 'RNPractice-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
